services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tomcat1
      - tomcat2
    networks:
      - app-net

  tomcat1:
    build: ./tomcat
    container_name: woori-card-tomcat1
    environment:
      JVM_ROUTE: tomcat1
      CLUSTER_PORT: 4001

      DB_WRITE_HOST: woori-mysql-source
      DB_WRITE_PORT: "3306"
      DB_WRITE_NAME: ${MYSQL_DATABASE}
      DB_WRITE_USER: ${MYSQL_USER}
      DB_WRITE_PASSWORD: ${MYSQL_PASSWORD}

      DB_READ_HOST: woori-mysql-replica
      DB_READ_PORT: "3306"
      DB_READ_NAME: ${MYSQL_DATABASE}
      DB_READ_USER: ${MYSQL_USER}
      DB_READ_PASSWORD: ${MYSQL_PASSWORD}

    depends_on:
      woori-mysql-source:
        condition: service_healthy
      woori-mysql-replica:
        condition: service_healthy
    networks:
      - app-net

  tomcat2:
    build: ./tomcat
    container_name: woori-card-tomcat2
    environment:
      JVM_ROUTE: tomcat2
      CLUSTER_PORT: 4002

      DB_WRITE_HOST: woori-mysql-source
      DB_WRITE_PORT: "3306"
      DB_WRITE_NAME: ${MYSQL_DATABASE}
      DB_WRITE_USER: ${MYSQL_USER}
      DB_WRITE_PASSWORD: ${MYSQL_PASSWORD}

      DB_READ_HOST: woori-mysql-replica
      DB_READ_PORT: "3306"
      DB_READ_NAME: ${MYSQL_DATABASE}
      DB_READ_USER: ${MYSQL_USER}
      DB_READ_PASSWORD: ${MYSQL_PASSWORD}

    depends_on:
      woori-mysql-source:
        condition: service_healthy
      woori-mysql-replica:
        condition: service_healthy
    networks:
      - app-net

  woori-mysql-source:
    build: ./db/source
    container_name: woori-card-mysql-source
    hostname: woori-mysql-source
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${SOURCE_PORT}:3306"
    volumes:
      - mysql_source_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - app-net

  woori-mysql-replica:
    build: ./db/replica
    container_name: woori-card-mysql-replica
    hostname: woori-mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${REPLICA_PORT}:3306"
    volumes:
      - mysql_replica_data:/var/lib/mysql
    depends_on:
      woori-mysql-source:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - app-net

volumes:
  mysql_source_data:
  mysql_replica_data:

networks:
  app-net:
    driver: bridge