services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-net

  woori-mysql-source:
    build: ./db/source
    container_name: woori-card-mysql-source
    hostname: woori-mysql-source
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${SOURCE_PORT}:3306"
    volumes:
      - mysql_source_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - app-net

  woori-mysql-replica:
    build: ./db/replica
    container_name: woori-card-mysql-replica
    hostname: woori-mysql-replica
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${REPLICA_PORT}:3306"
    volumes:
      - mysql_replica_data:/var/lib/mysql
    depends_on:
      woori-mysql-source:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - app-net

volumes:
  mysql_source_data:
  mysql_replica_data:

networks:
  app-net:
    driver: bridge
